-- Initial migration to create all tables and relationships
-- This will be generated by Prisma migrate dev

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- Enums
CREATE TYPE "court_type" AS ENUM ('MAGISTRATE', 'HIGH_COURT', 'TRIBUNAL', 'OTHER');
CREATE TYPE "case_status" AS ENUM ('ACTIVE', 'RESOLVED', 'PENDING', 'TRANSFERRED', 'DELETED');
CREATE TYPE "custody_status" AS ENUM ('IN_CUSTODY', 'ON_BAIL', 'NOT_APPLICABLE');
CREATE TYPE "import_status" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');
CREATE TYPE "user_role" AS ENUM ('ADMIN', 'DATA_ENTRY', 'VIEWER');

-- Tables
CREATE TABLE "courts" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "court_name" VARCHAR(255) NOT NULL,
    "court_code" VARCHAR(50) NOT NULL,
    "court_type" "court_type" NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "courts_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "judges" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "full_name" VARCHAR(255) NOT NULL,
    "first_name" VARCHAR(100) NOT NULL,
    "last_name" VARCHAR(100) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "judges_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "case_types" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "case_type_name" VARCHAR(100) NOT NULL,
    "case_type_code" VARCHAR(20) NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "case_types_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "email" VARCHAR(255) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "role" "user_role" NOT NULL DEFAULT 'DATA_ENTRY',
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "daily_import_batches" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "import_date" DATE NOT NULL,
    "filename" VARCHAR(255) NOT NULL,
    "file_size" INTEGER NOT NULL,
    "file_checksum" VARCHAR(64) NOT NULL,
    "total_records" INTEGER NOT NULL,
    "successful_records" INTEGER NOT NULL,
    "failed_records" INTEGER NOT NULL,
    "error_logs" JSONB NOT NULL,
    "status" "import_status" NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMP(3),
    "created_by" UUID NOT NULL,

    CONSTRAINT "daily_import_batches_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "cases" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "case_number" VARCHAR(50) NOT NULL,
    "case_type_id" UUID NOT NULL,
    "filed_date" DATE NOT NULL,
    "original_court_id" UUID,
    "original_case_number" VARCHAR(50),
    "original_year" INTEGER,
    "parties" JSONB NOT NULL,
    "status" "case_status" NOT NULL DEFAULT 'ACTIVE',
    "case_age_days" INTEGER NOT NULL DEFAULT 0,
    "last_activity_date" TIMESTAMP(3),
    "total_activities" INTEGER NOT NULL DEFAULT 0,
    "has_legal_representation" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cases_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "case_activities" (
    "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
    "case_id" UUID NOT NULL,
    "activity_date" DATE NOT NULL,
    "activity_type" VARCHAR(100) NOT NULL,
    "outcome" VARCHAR(100) NOT NULL,
    "reason_for_adjournment" TEXT,
    "next_hearing_date" DATE,
    "primary_judge_id" UUID NOT NULL,
    "has_legal_representation" BOOLEAN NOT NULL,
    "applicant_witnesses" INTEGER NOT NULL DEFAULT 0,
    "defendant_witnesses" INTEGER NOT NULL DEFAULT 0,
    "custody_status" "custody_status" NOT NULL,
    "details" TEXT,
    "import_batch_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "case_activities_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "case_judge_assignments" (
    "case_id" UUID NOT NULL,
    "judge_id" UUID NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_primary" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "case_judge_assignments_pkey" PRIMARY KEY ("case_id","judge_id")
);

-- Unique constraints
CREATE UNIQUE INDEX "courts_court_code_key" ON "courts"("court_code");
CREATE UNIQUE INDEX "case_types_case_type_code_key" ON "case_types"("case_type_code");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "cases_case_number_key" ON "cases"("case_number");

-- Foreign Key Constraints
ALTER TABLE "daily_import_batches" ADD CONSTRAINT "daily_import_batches_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "cases" ADD CONSTRAINT "cases_case_type_id_fkey" FOREIGN KEY ("case_type_id") REFERENCES "case_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "cases" ADD CONSTRAINT "cases_original_court_id_fkey" FOREIGN KEY ("original_court_id") REFERENCES "courts"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "case_activities" ADD CONSTRAINT "case_activities_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "case_activities" ADD CONSTRAINT "case_activities_primary_judge_id_fkey" FOREIGN KEY ("primary_judge_id") REFERENCES "judges"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "case_activities" ADD CONSTRAINT "case_activities_import_batch_id_fkey" FOREIGN KEY ("import_batch_id") REFERENCES "daily_import_batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "case_judge_assignments" ADD CONSTRAINT "case_judge_assignments_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "case_judge_assignments" ADD CONSTRAINT "case_judge_assignments_judge_id_fkey" FOREIGN KEY ("judge_id") REFERENCES "judges"("id") ON DELETE RESTRICT ON UPDATE CASCADE;